Fix comment and hint message

diff --git a/bin/git-id b/bin/git-id
--- a/bin/git-id
+++ b/bin/git-id
@@ -3,8 +3,8 @@
 # List or switch git ids (user.name and user.email) defined in ~/.git-ids,
 # for example, define ~/.git-ids as below:
 #
-#   github ymattw@example.com ymattw
-#   corp matt@example.org matt
+#   github ymattw@example.com Matthew Wang
+#   corp matt@example.org Matthew Y Wang
 #
 # Then you can run 'git-id github' to setup user.name and user.email to your
 # github account and run 'git-id corp' to switch to your corp account.
@@ -16,7 +16,7 @@ readonly GIT_ID_FILE=~/.git-ids
 readonly ID=${1:-""}
 
 [[ -r $GIT_ID_FILE ]] || {
-    echo "$GIT_ID_FILE not found, define your ids as 'email first last'" >&2
+    echo "$GIT_ID_FILE not found, define your ids as 'id email first last'" >&2
     echo "there (one id per line) to switch id quickly" >&2
     exit 0
 }
