more clean PS1

diff --git a/bashrc-y b/bashrc-y
--- a/bashrc-y
+++ b/bashrc-y
@@ -40,41 +40,49 @@ function __git_active_branch() {
 #      | sed '/^echo/d' > /home/$U/.ssh-agent.rc"
 # You will need to ssh-add your identity manually once
 #
-PS1='\[$([[ $? == 0 ]] && echo "\e[1;32m✔\e[0m" || echo "\e[1;31m✘\e[0m"\]) '
+_LR="\[\e[1;31m\]"      # light red
+_LG="\[\e[1;32m\]"      # light green
+_LY="\[\e[1;33m\]"      # light yellow
+_LB="\[\e[1;34m\]"      # light blue
+_HU="\[\e[0;1;4m\]"     # hilight, underline
+_RR="\[\e[7;31m\]"      # reverse red
+_NC="\[\e[0m\]"         # no color
+
+# Start from exit status of last command
+PS1="\$([[ \$? == 0 ]] && echo '${_LG}✔${_NC}' || echo '${_LR}✘${_NC}') "
+PS1="${PS1}${_HU}"                                  # then init to hi/ul
 
 if [[ -f ~/.ssh-agent.rc ]]; then
-    # I am on my own machine, set initial PS1 to ansi hi and ul (default to
-    # black) and try load ssh-agent related environments
-    #
-    PS1="$PS1"'\[\e[1;4m\]' # ansi hi & ul
-
+    # I am on my own machine, try load ssh-agent related environments
     . ~/.ssh-agent.rc
     if [[ -d /proc/${SSH_AGENT_PID:-0} ]]; then
         if ! ssh-add -l >& /dev/null; then
-            echo -e "\e[1;31mWarning: No key is being held by ssh-agent," \
-                    "try 'ssh-add <your-ssh-private-key>'\e[0m" >&2
+            echo -e "\x1b[1;31mWarning: No key is being held by ssh-agent," \
+                    "try 'ssh-add <your-ssh-private-key>'\x1b[0m" >&2
         fi
     else
-        echo -e "\e[1;31mWarning: Global ssh-agent is not alive," \
-                "please review /etc/rc.d/rc.local\e[0m" >&2
+        echo -e "\x1b[1;31mWarning: Global ssh-agent is not alive," \
+                "please review /etc/rc.d/rc.local\x1b[0m" >&2
     fi
 else
-    # Otherwise assume I am on other's box, highlight PS1 in red as well
-    PS1="$PS1"'\[\e[1;4;31m\]'  # ansi hi, ui and red
+    # Otherwise assume I am on other's box, highlight hostname in red
+    PS1="${PS1}${_LR}"
 fi
 
 # Fancy PS1, prompt current yroot, also prompt the '$' in red when we have
 # background jobs, '\[' and '\]' is to mark ansi colors to allow shell to
 # calculate prompt string length correctly
 #
-PS1="$PS1"'$(_H=${HOSTNAME%.yahoo.*}; echo ${_H%.peking.corp})' # short hostname
-PS1="$PS1"'\[\e[32m\]'                                          # green
-PS1="$PS1"'$([[ -z $YROOT_NAME ]] || echo "{$YROOT_NAME}")'     # {yroot}
-PS1="$PS1"'\[\e[0;1;4m\]'                                       # reset color
-PS1="$PS1"':\w '                                                # cwd, new line
-PS1="$PS1"'\[\e[33m$(__git_active_branch)\e[0m\]'               # yellow branch
-PS1="$PS1"'\[$([[ -z $(jobs) ]] || echo "\e[7;31m")\]'          # reverse jobs
-PS1="$PS1"'\$\[\e[0m\] '                                        # $, end color
+PS1="${PS1}$(_H=${HOSTNAME%.yahoo.*}; echo ${_H%.peking.corp})"
+PS1="${PS1}${_LG}"                                  # then green {yroot}
+PS1="${PS1}"'$([[ -z $YROOT_NAME ]] || echo "{$YROOT_NAME}")'
+PS1="${PS1}${_HU}"                                  # reset back to hi/ul
+PS1="${PS1} \w "                                    # cwd
+PS1="${PS1}${_LY}\$(__git_active_branch)${_NC}"     # yellow git branch
+PS1="${PS1}\$([[ -z \$(jobs) ]] || echo '$_RR')"    # reverse bg job indicator
+PS1="${PS1}\\\$${_NC} "                             # $
+unset  _LR _LG _LY _LB _HU _RR _NC
+
 export PS1
 export EDITOR=vim
 export TERM=linux
