Mirror latest zshrc to bashrc

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -7,27 +7,29 @@
 # - Functions with name starts with only one '_' are considered 'protected',
 #   users can implement their own to override (via ~/.profiles.d).
 
-# Find a file which name matches given pattern (ERE, case insensitive)
-function f
-{
-    local pat=${1?'Usage: f ERE-pattern [path...]'}
-    shift
-    find ${@:-.} \( -path '*/.svn' -o -path '*/.git' -o -path '*/.idea' \) \
-        -prune -o -print -follow | grep -iE "$pat"
-}
-
-# Load file list generated by f() in vim, type 'gf' to jump to the file
+# Example usage:
+#   vif                       # pick files from ~/.fzf-file-list, send to vim
+#   vif path [...]            # pick files from path..., send to vim
+#   vif | cmd                 # pick files from ~/.fzf-file-list, send to cmd
+#   vif path [...] | xargs .. # pick files from path..., send to xargs cmd
+#   hg ls | vif               # pick files from commd output, send to vim
 function vif
 {
-    local tmpf=/tmp/viftmpfile.$RANDOM$$
-    f "$@" > $tmpf && vi -c "/$1" $tmpf && rm -f $tmpf
-}
-
-# Execute a command, pipe output to fzf and load result file into vi (alias).
-# Get fzf at https://github.com/junegunn/fzf. Example: vio hg ls
-function vio
-{
-    vi $("$@" | fzf || echo +q)
+    if type nvim >& /dev/null; then
+        local arg=(--bind "enter:become(nvim -n {})")
+    else
+        local arg=(--bind "enter:become(vim -Xn -u ~/.vimrc {})")
+    fi
+    [[ -t 1 ]] || arg=()
+    if [[ -t 0 ]]; then
+        if (( $# > 0 )); then
+            find "$@" -type f | fzf "${arg[@]}"
+        else
+            fzf "${arg[@]}" < ~/.fzf-file-list
+        fi
+    else
+        fzf "${arg[@]}"
+    fi
 }
 
 # "Protected" helper to decorate CWD used to setup PS1
@@ -43,7 +45,7 @@ function _source_control_cwd
 #
 function _source_control_info
 {
-    if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]; then
+    if [[ $(GIT_CEILING_DIRECTORIES=$HOME git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]; then
         _git_active_branch
     fi
 }
@@ -60,12 +62,15 @@ function _git_active_branch
 
     # NOTE: have to use $'string' for ansi escape sequence here
     if [[ -z $info ]]; then
-        echo -ne $'\e[32m'" ($branch) "$'\e[36m'"[${age}${track}]"
+        echo -ne $'\e[32m'
     elif [[ -z $(echo "$info" | grep -v '^??') ]]; then
-        echo -ne $'\e[35m'" ($branch) "$'\e[36m'"[${age}${track}]"
+        echo -ne $'\e[35m'
     else
-        echo -ne $'\e[31m'" ($branch) "$'\e[36m'"[${age}${track}]"
+        echo -ne $'\e[31m'
     fi
+
+    echo -n " ($branch) "
+    echo -ne $'\e[36m'"[${age}${track}]"
 }
 
 function __main
@@ -98,15 +103,29 @@ function __prepend_path
 
 function __setup_path
 {
-    local x
+    local d
 
-    # prepend paths
-    for x in /sbin /usr/sbin /bin /usr/bin /usr/local/bin; do
-        __prepend_path $x
+    for d in \
+        /sbin \
+        /usr/sbin \
+        /bin \
+        /usr/bin \
+        /usr/local/bin \
+        /opt/homebrew/bin \
+        ~/.local/bin \
+        ~/bin \
+    ; do
+        [[ -d $d ]] || continue
+
+        # Remove the directory from PATH if it already exists
+        PATH=":${PATH}:"
+        PATH="${PATH//:${d}:/:}"
+        PATH="${PATH#:}"
+        PATH="${PATH%:}"
+
+        # Prepend it to the front
+        [[ -z "$PATH" ]] && PATH="$d" || PATH="$d:$PATH"
     done
-
-    # ~/bin takes precedence
-    __prepend_path ~/bin
 
     export PATH
 }
@@ -119,63 +138,44 @@ function __setup_shell_options
 
 function __setup_environments
 {
-    export HISTFILE=~/.bash_history     # In case switched from zsh temporally
-    export HISTSIZE=10000
-    export EDITOR=vim
+    HISTFILE=~/.bash_history     # In case switched from zsh temporally
+    HISTSIZE=10000
+    export EDITOR=vi
+    ! type vim >& /dev/null || export EDITOR=vim
+    ! type nvim >& /dev/null || export EDITOR=nvim
 
     # Locale (LC_*) matters for ls and sort on Linux, see also
     # www.gnu.org/software/coreutils/faq/#Sort-does-not-sort-in-normal-order_0021
     #
-    [[ $(uname -s) != Linux ]] || export LC_COLLATE=C
-}
-
-# Non "private" helper function to auto complete hostnames, note 'complete -A
-# hostname' also works but it does not recognize new $HOSTFILE
-#
-function _host_complete
-{
-    local cur=${COMP_WORDS[COMP_CWORD]}
-    local hosts=$(sed -ne 's/[, ].*//p' ~/.ssh/known_hosts* 2>/dev/null)
-    COMPREPLY=($(compgen -W "$hosts" -- $cur))
+    [[ $OSTYPE != linux* ]] || export LC_COLLATE=C
 }
 
 function __setup_completions
 {
     # git-completion.bash is installed by install.sh
     [[ ! -f ~/.git-completion.bash ]] || . ~/.git-completion.bash
-    complete -F _host_complete ssh scp host nc ping telnet
     complete -A export unset
 }
 
 function __setup_aliases
 {
-    local lsprog="/bin/ls"
-
     alias ..='cd ..'
     alias ...='cd ../..'
     alias ....='cd ../../..'
     alias .....='cd ../../../..'
     # Skip system wide vimrc to reduce startup time
     ! type vim >& /dev/null || alias vi='vim -Xn -u ~/.vimrc'
-    ! type ag >& /dev/null || alias ag='command ag --nogroup'
+    ! type nvim >& /dev/null || alias vi='nvim'
     alias grep='grep --color=auto'
+    alias ls="/bin/ls -F --color=auto"
+    alias l="/bin/ls -lF --color=auto"
 
-    case $(uname -s) in
-        Linux)
-            lsprog="/bin/ls --color=auto"
-            alias ls="$lsprog -F"
-            alias l="$lsprog -lF"
-            alias lsps='ps -ef f | grep -vw grep | grep -i'
-            ;;
-        Darwin)
-            type gls >& /dev/null && lsprog="gls --color=auto"
-            alias ls="$lsprog -F"
-            alias l="$lsprog -lF"
+    case $OSTYPE in
+        darwin*)
+            export LSCOLORS="exgxfxfxcxdxdxbxbxcxbx"
             alias lsps='ps -ax -o user,pid,ppid,stime,tty,time,command | grep -vw grep | grep -i'
             ;;
         *)
-            alias ls="$lsprog -F"
-            alias l="$lsprog -lF"
             alias lsps='ps -auf | grep -vw grep | grep -i'
             ;;
     esac
@@ -185,48 +185,39 @@ function __setup_dir_colors
 {
     local prog=dircolors
 
-    [[ $(uname -s) != Darwin ]] || prog=gdircolors
+    [[ $OSTYPE != darwin* ]] || prog=gdircolors
     if type $prog >& /dev/null && [[ -f ~/.dircolors ]]; then
         eval $($prog -b ~/.dircolors)
     fi
 }
 
-function __has_ssh_key
-{
-    [[ -f ~/.ssh/$USER.key ]] || ls ~/.ssh/id_?sa >& /dev/null
-}
-
-function __load_ssh_key
-{
-    [[ ! -f "${1:?}" ]] || ssh-add -L | grep -qw "$1" || ssh-add "$1"
-}
-
-# ssh-add -l exits code 2 when unable to connect to the agent
 function __setup_ssh_agent
 {
-    local rc=~/.ssh-agent.rc
+    # NOTE for gMac: create a wrapper ~/bin/ssh (with symlink scp, sftp etc.)
+    # as below to work better. See also ../ssh/config.sample.
+    #
+    # if echo "$*" | grep -qE "someCorpHostPattern"; then
+    #     /usr/local/bin/$(basename $0) -o PubkeyAcceptedAlgorithms=ecdsa-sha2-nistp256-cert-v01@openssh.com "$@"
+    # else
+    #     /usr//bin/$(basename $0) -o PubkeyAcceptedAlgorithms=ssh-ed25519 "$@"
+    # fi
 
-    # Skip in typical corporation environment
-    [[ -z $SK_SIGNING_PLUGIN ]] || return 0
+    local key=~/.ssh/$USER.key
 
-    __has_ssh_key || return 0
-    [[ ! -f $rc ]] || source $rc
-    if [[ $(ssh-add -l >& /dev/null; echo $?) == 2 ]]; then
-        print -P "%{\e[31m%}Starting a new ssh-agent process...%{\e[0m}" >&2
-        rm -f ~/.ssh-agent.sock
-        ssh-agent -s -a ~/.ssh-agent.sock | sed '/^echo/d' > $rc
-        source $rc
-    fi
-
-    __load_ssh_key ~/.ssh/$USER.key
-    __load_ssh_key ~/.ssh/id_rsa
-    __load_ssh_key ~/.ssh/id_dsa
+    [[ -f $key ]] || return 0
+    # Modern OS should have a global ssh-agent set up already.
+    ! /usr/bin/ssh-add -L | grep -q '^ssh' || return 0
+    /usr/bin/ssh-add "$key" || {
+        print -P "%F{red}Error adding $key; check \$SSH_AUTH_SOCK and ssh-agent process!%f" >&2
+        return 1
+    }
 }
 
 # Fancy PS1, prompt exit status of last command, currenet time, hostname, time,
-# cwd, git status and branch, also prompt the '%' in reverse color when we have
+# cwd, git status and branch, also prompt the '$' in reverse color when we have
 # background jobs. '\[' and '\]' is to mark ansi colors to allow shell to
-# calculate prompt string length correctly
+# calculate prompt string length correctly. NOTE: some symbols may not show
+# correctly inside tmux, run tmux with option "-u" should fix it.
 #
 function __setup_prompt
 {
@@ -238,33 +229,35 @@ function __setup_prompt
     local _DC="\[\e[36m\]"        # cyan
     local _RV="\[\e[7m\]"         # reverse
     local _NC="\[\e[0m\]"         # no color
+    local _118="\[\e[38;5;118m\]" # color 118
 
-    PS1="\n\$([[ \$? == 0 ]] && echo '${_DG}✔' || echo '${_DR}✘') \t "
+    local distro
 
-    # Detect whether this box has ssh keys, distinguish hostname color and setup
-    # ssh-agent related environment accordingly
-    #
-    if __has_ssh_key; then
-        # I am on my own machine, try load ssh-agent related environments
-        PS1="${PS1}${_DB}"                              # blue hostname
+    if [[ $OSTYPE == darwin* ]]; then
+        __OS_ICON=$'\uf179' # macOS
     else
-        # Otherwise assume I am on other's box, highlight hostname in magenta
-        PS1="${PS1}${_DM}"                              # magenta hostname
+        IFS='=' read -r _ distro < <(grep "^ID=" /etc/os-release 2>/dev/null)
+
+        # Match the distro ID to a Nerd Font __OS_ICON
+        # Ref: https://www.nerdfonts.com/cheat-sheet
+        case "$distro" in
+            debian) __OS_ICON=$'\uf306' ;;
+            ubuntu) __OS_ICON=$'\uf31b' ;;
+            *)      __OS_ICON=$'\uf31a' ;;  # Linux Tux
+        esac
     fi
 
-    # Highlight hostname in reverse green if inside a container
-    if [[ -n $container_uuid ]] || [[ -f /.dockerenv ]]; then
-        PS1="${PS1}${_RV}${_DG}"
-    fi
-    PS1="${PS1}$(hostname -f | cut -d. -f1-2)"          # 2 hostname components
-    PS1="${PS1}${_NC}:${_DY}\$(_source_control_cwd)"    # yellow cwd
-    PS1="${PS1}${_NC}\$(_source_control_info)"          # source control info
-    PS1="${PS1}${_DC} ⤾\n"                              # cyan wrap char, NL
-    PS1="${PS1}\$([[ -z \$(jobs) ]] || echo '$_RV')"    # reverse bg job
-    PS1="${PS1}\\\$${_NC} "                             # $ or #
+    PS1="\$([[ \$? == 0 ]] && echo '${_DG}✔' || echo '${_DR}✘') \t${_NC} "
+                                                        # exit code and time
+    PS1+="${_DY}\$(_source_control_cwd)${_NC}"          # yellow cwd
+    PS1+="\$(_source_control_info)"                     # vcs info
+    PS1+=" ${_DC}⤾\n"                                   # cyan wrap char, NL
+    PS1+="${_118}${__OS_ICON}${_NC} ${HOSTNAME%%.*}"    # OS icon, hostname
+    PS1+=" \$([[ -z \$(jobs) ]] || echo '$_RV')"        # reverse bg job
+    PS1+='\[\e[1m\]\$'"${_NC} "                         # $ or #
 }
 
-# Load custom settings from ~/.profile.d/*.sh, typical settings are
+# Load custom settings from ~/.profiles.d/*.sh, typical settings are
 # docker-machine env, GOPATH, customized PATH etc.
 #
 function __setup_custom_profiles
@@ -274,7 +267,7 @@ function __setup_custom_profiles
     ls ~/.profiles.d/*.sh >& /dev/null || return 0
 
     for p in ~/.profiles.d/*.sh; do
-        source $p
+        source "$p"
     done
 }
 
@@ -283,6 +276,6 @@ function __setup_custom_profiles
 ########################################################################
 
 __main
-unset -f __prepend_path __has_ssh_key __load_ssh_key __main
+unset -f __main
 
-# vim:set et sts=4 sw=4 ft=sh:
+# vim:set et sts=4 sw=4 ft=bash:
